name       : psycopg2
version    : 2.9.1
release    : 9
source     :
    - https://github.com/psycopg/psycopg2/archive/refs/tags/2_9_1.tar.gz : 3203b5b1bd903c5565e31af44b9206b9478463ea4bcf92809ad6d72261e08aaa
license    : LGPL-3.0-or-later
component  : programming.python
summary    : Psycopg is the most popular PostgreSQL adapter for the Python programming language
description: |
    Psycopg is the most popular PostgreSQL adapter for the Python programming language.
    At its core it fully implements the Python DB API 2.0 specifications.
    Several extensions allow access to many of the features offered by PostgreSQL.
builddeps  :
    - pkgconfig(libpq)
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install

