name       : psycopg2
version    : 2.9.7
release    : 16
source     :
    - https://github.com/psycopg/psycopg2/archive/refs/tags/2.9.7.tar.gz : 36c065b496ac5936f86c0407e0cc1633cea108f62dbca3648331ac138cb772c7
homepage   : https://www.psycopg.org/
license    : LGPL-3.0-or-later
component  : programming.python
summary    : Psycopg is the most popular PostgreSQL adapter for the Python programming language
description: |
    Psycopg is the most popular PostgreSQL adapter for the Python programming language. At its core it fully implements the Python DB API 2.0 specifications. Several extensions allow access to many of the features offered by PostgreSQL.
builddeps  :
    - pkgconfig(libpq)
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install

