name       : psycopg2
version    : 2.8.6
release    : 8
source     :
    - https://github.com/psycopg/psycopg2/archive/refs/tags/2_8_6.tar.gz : 8e04a3e8427ac135ccdc4fbd404561554a2a7aeeb6c15477b56941041f5ccf90
license    : LGPL-3.0-or-later
component  : programming.python
summary    : Psycopg is the most popular PostgreSQL adapter for the Python programming
    language
description: |
    Psycopg is the most popular PostgreSQL adapter for the Python programming language.
    At its core it fully implements the Python DB API 2.0 specifications.
    Several extensions allow access to many of the features offered by PostgreSQL.
builddeps  :
    - pkgconfig(libpq)
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install

