name       : psycopg2
version    : 2.7.4
release    : 4
source     :
    - http://initd.org/psycopg/tarballs/PSYCOPG-2-7/psycopg2-2.7.4.tar.gz : 8bf51191d60f6987482ef0cfe8511bbf4877a5aa7f313d7b488b53189cf26209
license    : LGPL-3.0
component  : programming.python
summary    : Psycopg is the most popular PostgreSQL adapter for the Python programming
    language
description: |
    Psycopg is the most popular PostgreSQL adapter for the Python programming language.
    At its core it fully implements the Python DB API 2.0 specifications.
    Several extensions allow access to many of the features offered by PostgreSQL.
builddeps  :
    - pkgconfig(libpq)
    - pkgconfig(python3)
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install

